### ISSUE TITLE
Messages that can be placed on ground / walls

### ISSUE THREAD

**Issue by GoncaloPascoal** [VenomPaco/ddjd-fp#16]
## To-Do

- [x] Display a button prompt when the player gets close to the message
- [x] Show message on screen
- [x] Close message when player gets too far or presses a button
