### ISSUE TITLE
Health system implementation

### ISSUE THREAD

**Issue by GoncaloPascoal** [VenomPaco/ddjd-fp#22]
## To-Do
- [x] Add `OnHealthChanged` event to `Hittable` / `Damageable` class
- [x] Link player health bar with event
- [x] Add health bars over enemies
- [x] Link enemy health bars with event
- [x] Use global canvas instead of a canvas per enemy
