### ISSUE TITLE
Death animation and respawn

### ISSUE THREAD

**Issue by GoncaloPascoal** [VenomPaco/ddjd-fp#99]
## To-Do

- [x] Player death animation
- [x] Disable controls
- [x] Fade out screen
- [x] Respawn at last checkpoint
